(<class 'ImportError'>, ImportError("cannot import name 'User' from partially initialized module 'models' (most likely due to a circular import) (/home/edo/geekhouse/models.py)"), <traceback object at 0x7fe69c68f3c0>)
chatgpt is bad